os: linux
dist: xenial

language: java
jdk: openjdk11

before_install:
  - cp .ci/settings.xml $HOME/.m2/settings.xml
  - echo $GPG_PRIVATE_KEY | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install: mvn clean package -Dgpg.skip -Dmaven.javadoc.skip=true -B -U

deploy:
  - provider: script
    script: mvn deploy -DskipTests=true -B -U -DdeployAtEnd=true \
      -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/finarkein/finarkein-auth \
      -Prelease
    cleanup: false
    on:
      tags: true
  - provider: script
    script: mvn deploy -DskipTests=true -B -U -DdeployAtEnd=true \
      -DaltReleaseDeploymentRepository=ossrh::https://oss.sonatype.org/service/local/staging/deploy/maven2 \
      -DaltSnapshotDeploymentRepository=ossrh::https://oss.sonatype.org/content/repositories/snapshots \
      -Prelease
    cleanup: false
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|main|develop)$

cache:
  directories:
    - ~/.m2/repository